import type { Metadata } from "next";
import { Fragment } from "react/jsx-runtime";

export const metadata: Metadata = {
  title: "About | MagMag Next.JS APP",
  description: "Generated by MagMag :D",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Fragment>
        {children}
    </Fragment>
  );
}
